packages:
  - examples/*
  - docs
  - .

catalog:
  tailwindcss: ^4.1.11
  postcss: ^8.5.6
  autoprefixer: ^10.4.21
  '@tailwindcss/typography': ^0.5.16
  react: ^18.3.1
  react-dom: ^18.3.1
  lucide-react: 0.525.0
  typescript: ^5.8.3
  astro: ^5.10.1
  vite: ^6.3.5
  canvas-confetti: ^1.9.2
  '@types/react': ^18.3.23
  '@types/react-dom': ^18.2.18
  sass: ^1.89.2
  chrome-types: ^0.1.357
  '@types/node': ^22.10.1
  '@tailwindcss/vite': ^4.1.11
