name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21.x'
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Check types
        run: pnpm run lint
      
      - name: Run tests with coverage
        run: pnpm run test:coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: oe/postcss-logical-polyfill
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Build
        run: pnpm run build
      - name: Build website
        run: cd docs && pnpm run build
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: okarl@outlook.com
          branch: gh-pages   # optional
          build_dir: docs/dist # folder the action should deploy.
          jekyll: no
